env:
    TMATE: https://raw.githubusercontent.com/yash3056/ci-tmate/main/tmate
    SPAM: https://raw.githubusercontent.com/XelXen/Ubuntu-Tmate/master/spam.sh 

task:
  name: "CIRRUS SSH"
  timeout_in: 960m  
  container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
        
  Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - df -h
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y
       - sudo apt install software-properties-common -y
       - sudo add-apt-repository ppa:openjdk-r/ppa -y
       - sudo apt-get install python3 git gnupg flex bison wget python-is-python3 build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig clang ccache git aria2 nano tmux screen xclip silversearch* -y
       - git config --global user.name "Jprimero15"
       - git config --global user.email "jprimero155@gmail.com"
       - mkdir ~/bin
       - PATH=~/bin:$PATH
       - cd ~/bin 
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
       - sudo apt-get install tmate -y
  
  SSH_script:
      - curl $TMATE >> ~/tmate.sh
      - source ~/tmate.sh | tee
  
  Spam_script:
      - wget $SPAM
      - sh spam.sh
