#!/bin/bash
cd /tmp/rom

source build/envsetup.sh
lunch lineage_whyred-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

mka api-stubs-docs || echo no problem, we need ccache
mka system-api-stubs-docs || echo no problem we need ccache
mka test-api-stubs-docs || echo no problem, we need ccache
mka bacon -j$(nproc --all)
sleep 85m
kill %1
ccache -s
