#!/bin/bash
cd /tmp/rom

echo "██████╗ ██╗   ██╗██╗██╗     ██████╗ ";
echo "██╔══██╗██║   ██║██║██║     ██╔══██╗";
echo "██████╔╝██║   ██║██║██║     ██║  ██║";
echo "██╔══██╗██║   ██║██║██║     ██║  ██║";
echo "██████╔╝╚██████╔╝██║███████╗██████╔╝";
echo "╚═════╝  ╚═════╝ ╚═╝╚══════╝╚═════╝";
echo "You have: $(nproc --all) Core";

source build/envsetup.sh
lunch aosp_whyred-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

make api-stubs-docs || echo no problem, we need ccache
make system-api-stubs-docs || echo no problem we need ccache
make test-api-stubs-docs || echo no problem, we need ccache
mka bacon -j$(nproc --all) &
sleep 35m
kill %1
ccache -s
