#!/bin/bash
df -h
free -h
lscpu
nproc
cat /etc/os*
env

sudo apt install wget -y

url=https://aosp.polarisdp.workers.dev/ccache.tar.gz

cd /tmp
rm -rf ccache.tar.gz
# wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1NSOBFfpgjx5dQclFnDfbRFb0SBWeovID' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1NSOBFfpgjx5dQclFnDfbRFb0SBWeovID" -O ccache.tar.gz && rm -rf /tmp/cookies.txt
ls -lash
time aria2c $url -x16 -s50
time tar xf ccache.tar.gz
rm -rf ccache.tar.gz
