#!/bin/bash

cd /tmp

com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf
time rclone copy ccache.tar.gz doraemon: -P

cd /tmp/rom/out/target/product/whyred

time rclone copy lineage*whyred.zip doraemon:mirrors/LineageOS -P
