#!/bin/bash

cd /tmp/rom


# com() 
# { 
#     tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
# }

# time com ccache 1

tar -czvf out.tar.gz out

mkdir -p ~/.config/rclone

echo "$rclone_config" > ~/.config/rclone/rclone.conf

ls -lash

time rclone copy -v out.tar.gz doraemon:

cd /tmp/rom/out/target/product/whyred

time rclone copy -v lineage*whyred.zip doraemon:
